objects = src/main.o src/parser.o src/opts.o
autogenerated = src/opts.c src/opts.h

.PHONY : clean

boxing : $(objects)
	cc $(CFLAGS) -o boxing $(objects)

$(autogenerated) : src/opts.ggo
	cd src; gengetopt -i opts.ggo -F opts --unnamed-opts

src/opts.o : src/opts.c src/opts.h	
src/main.o : src/main.c src/opts.h src/parser.h
src/parser.o : src/parser.c src/parser.h

clean :
	rm -f boxing $(objects) $(autogenerated)

install :
	cp boxing /usr/local/bin

uninstall :
	rm -f /usr/local/bin/boxing
